# Generated by Django 5.2.7 on 2025-10-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show_user_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.CharField(max_length=4, verbose_name='性别')),
            ],
            options={
                'verbose_name': 'user_informations',
                'db_table': 'user_informations',
            },
        ),
    ]
